
spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Europe/Minsk
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: detect

log4jdbc:
  drivers: com.mysql.cj.jdbc.Driver
  auto:
    load:
      popular:
        drivers: false

logging:
  level:
    root: INFO
    org:
      springframework.orm.jpa: TRACE
      springframework.transaction: TRACE
      hibernate:
        engine:
          internal:
            StatefulPersistenceContext: ERROR
    jdbc:
      sqlonly: OFF
      sqltiming: INFO
      audit: OFF
      resultsettable: INFO
      resultset: OFF
      connection: OFF


server:
  servlet:
    context-path: /api/v1